
server:
  port: 9085
spring:
  application:
    name: mqbroker
  datasource:
    url: jdbc:mysql://localhost:3306/mq_basic?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 123456
    tomcat:
      max-active: 100
      initial-size: 10
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
#mybatis:
#  mapper-locations: classpath:mapper/*.xml
#  configuration:
#    map-underscore-to-camel-case: true